<?php 
// ------------------------------------------------------------------------ //
// Zarilia - PHP Content Management System                      			//
// Copyright (c) 2007 Zarilia                           					//
// //
// Authors: 																//
// John Neill ( AKA Catzwolf )                                     			//
// Raimondas Rimkevicius ( AKA Mekdrop )									//
// //
// URL: http:www.zarilia.com 												//
// Project: Zarilia Project                                               	//
// -------------------------------------------------------------------------//

/** DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING: YOU COULD SHUTDOWN YOUR SITE!!**/

 $cpConfig = array (
  'db' => 
  array (
    'type' => 'mysql',
    'prefix' => 'perchatenpo',
    'host' => 'localhost',
    'user' => 'root',
    'pass' => '',
    'name' => 'zarilia',
    'pconnect' => '0',
  ),
  'sites' => 
  array (
    'default://' => 
    array (
      'languages' => 
      array (
        0 => 'en',
      ),
      'prefix' => '852b3',
      'url' => 'http://localhost/zarilia',
    ),
  ),
  'tables' => 
  array (
    'ml' => 
    array (
    ),
    'ms' => 
    array (
      0 => 'configoption',
      1 => 'config',
      2 => 'events',
      3 => 'group_permission',
      4 => 'groups',
      5 => 'groups_users_link',
      6 => 'language_base',
      7 => 'language_ext',
      8 => 'addons',
      9 => 'newblocks',
      10 => 'online',
      11 => 'tplfile',
      12 => 'tplset',
      13 => 'tplsource',
    ),
  ),
  'groups' => 
  array (
    1 => 'ADMIN',
    2 => 'USERS',
    3 => 'ANONYMOUS',
    4 => 'MODERATORS',
    5 => 'SUBMITTERS',
    6 => 'SUBSCRIPTION',
    7 => 'BANNED',
  ),
  'root_path' => 'C:/PHPLearnWAMP/Apache2/htdocs/zarilia',
  'check_path' => 1,
);
?>